export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  CHANGE_PASSWORD: '/settings/change-password',
  UNAUTHORIZED: '/unauthorized',
  NOT_FOUND: '/404',
  ADMIN_DASHBOARD: '/admin/dashboard',
  STUDIOS: '/admin/studios',
  STUDIO_CREATE: '/admin/studios/new',
  STUDIO_EDIT: '/admin/studios/:id/edit',
  STUDIO_DETAILS: '/admin/studios/:id',
  STUDIO_PROFILE: '/studio/profile',
  STUDIO_PLAN: '/studio/plan',
  STUDIO_BILLING: '/studio/billing',
  ALBUMS: '/studio/albums',
  ALBUM_CREATE: '/studio/albums/new',
  ALBUM_EDIT: '/studio/albums/:id/edit',
  ALBUM_DETAILS: '/studio/albums/:id',
  ALBUM_MEDIA: '/studio/albums/:id/media',
  ALBUM_AR_MAPPINGS: '/studio/albums/:id/ar-mappings',
  ALBUM_AR_MAPPING_CREATE: '/studio/albums/:id/ar-mappings/new',
  ALBUM_AR_MAPPING_EDIT: '/studio/albums/:id/ar-mappings/:mappingId/edit',
  VIEWER: '/viewer/:albumSlug',
  STUDIO_ANALYTICS: '/studio/analytics',
  STUDIO_ANALYTICS_REPORTS: '/studio/analytics/reports',
  ALBUM_INSIGHTS: '/studio/albums/:id/insights',
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_ANALYTICS_REPORTS: '/admin/analytics/reports',
  PLANS: '/admin/plans',
  PLAN_CREATE: '/admin/plans/new',
  PLAN_EDIT: '/admin/plans/:id/edit',
  PLAN_DETAILS: '/admin/plans/:id',
  SUBSCRIPTIONS: '/admin/subscriptions',
  SUBSCRIPTION_DETAILS: '/admin/subscriptions/:id',
  ADMIN_BILLING: '/admin/billing',
  ADMIN_BILLING_PAYMENTS: '/admin/billing/payments',
  ADMIN_BILLING_INVOICES: '/admin/billing/invoices',
  ADMIN_BILLING_SUBSCRIPTIONS: '/admin/billing/subscriptions',
  NOTIFICATIONS: '/studio/notifications',
  ADMIN_JOBS: '/admin/jobs',
  ADMIN_NOTIFICATIONS: '/admin/notifications',
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
